### PR TITLE
Rails 5 belongs_to should use optional: true.

### PR DESCRIPTION
**Pull request by klacointe**
Rails 5 automatically adds a presence validation on belongs_to associations:

* https://github.com/rails/rails/issues/18233
* http://edgeapi.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Could you add a short description or link to documentation why this is needed?

**Comment by klacointe** [comment]
Sure, done

**Comment by felixbuenemann** [comment]
This will be fun when upgrading apps to rails 5…

Your changes look good to me, I'll cut a new release today or tomorrow.

**Comment by klacointe** [comment]
Thanks!

**Comment by felixbuenemann** [comment]
Just released 2.4.0. Thanks for your contribution!

**Pull request merged**
