### PR TITLE
block.call is about twice as slow as yield.

### PR DESCRIPTION
**Pull request by ioquatix**
http://stackoverflow.com/a/17670204/293815

### CODE REVIEW

**Comment by marshall-lee** [comment]
@ioquatix hi! have you measured this method? here we have a case that's not represented in benchmarks above since `&block` is still captured here that means a `Proc` object allocation anyway.

**Comment by ioquatix** [comment]
@marshall-lee Sorry dude I have not benchmarked it but I'm pretty sure yield will be a single opcode where as block.call would be more expensive.

**Comment by marshall-lee** [comment]
@ioquatix 

```ruby
require 'benchmark/ips'

def with_call(&block)
  block.call
end

def with_yield
  yield
end

def with_block_and_yield(&block)
  yield
end


Benchmark.ips do |x|
  x.report('with_call') do
    with_call { }
  end

  x.report('with_block_and_yield') do
    with_block_and_yield { }
  end

  x.report('with_yield') do
    with_yield { }
  end

  x.compare!
end
```
Results

```
Calculating -------------------------------------
           with_call    66.112k i/100ms
with_block_and_yield    71.294k i/100ms
          with_yield   102.156k i/100ms
-------------------------------------------------
           with_call      1.362M (± 0.7%) i/s -      6.810M
with_block_and_yield      1.594M (± 0.7%) i/s -      7.985M
          with_yield      4.639M (± 2.8%) i/s -     23.292M

Comparison:
          with_yield:  4638553.3 i/s
with_block_and_yield:  1593505.7 i/s - 2.91x slower
           with_call:  1362189.2 i/s - 3.41x slower
```

**Comment by marshall-lee** [comment]
`&block` allocation eats the most.  Soo... readability or performance?

**Comment by ioquatix** [comment]
I think yield is more readable.

```
#!/usr/bin/env ruby

require 'ostruct'
require 'benchmark/ips'

Node = Struct.new(:name, :children)

def walk_tree_dfs_call(node = nil, level = 0, &block)
	nodes = node.children
	
	nodes.each do |child|
		block.call(child, level)
		walk_tree_dfs_call(child, level + 1, &block)
	end
end

def walk_tree_dfs_yield(node = nil, level = 0, &block)
	nodes = node.children
	
	nodes.each do |child|
		yield(child, level)
		walk_tree_dfs_yield(child, level + 1, &block)
	end
end

def make_children(i = 8)
	return [] if i == 0
	
	i.times.collect do |j|
		Node.new("child #{j}", make_children(i-1))
	end
end

puts "Making children..."
top = Node.new('top', make_children)

Benchmark.ips do |x|
	x.report("dfs yield") do
		walk_tree_dfs_yield(top) {|child, level| level+1}
	end
	
	x.report("dfs call") do
		walk_tree_dfs_call(top) {|child, level| level+1}
	end
	
	# Compare the iterations per second of the various reports!
	x.compare!
end
```

```
Calculating -------------------------------------
           dfs yield     2.000  i/100ms
            dfs call     2.000  i/100ms
-------------------------------------------------
           dfs yield     34.531  (± 2.9%) i/s -    174.000 
            dfs call     25.641  (± 7.8%) i/s -    128.000 

Comparison:
           dfs yield:       34.5 i/s
            dfs call:       25.6 i/s - 1.35x slower
```

**Comment by ioquatix** [comment]
Haha... Even with an 8-deep tree, this was faster than the others by 20%

```
def walk_tree_dfs_yield_no_block(node = nil, level = 0)
	nodes = node.children
	
	nodes.each do |child|
		walk_tree_dfs_yield_no_block(child, level + 1) { yield }
	end
end
```

Ah Ruby.

**Comment by marshall-lee** [comment]
@ioquatix so i think this is good to get rid of redundant allocations of `Proc` for each node too. it's not only about cpu time, it's a memory issue too.

**Comment by felixbuenemann** [comment]
@marshall-lee The block is passed as an argument recursively. How would you get rid of it?

@ioquatix Does the speed difference really matter compared to the time spent loading and instantiating active record models and running the code inside the block?

**Comment by ioquatix** [comment]
It doesn't really matter, it just seemed non-idiomatic to me.

**Comment by ioquatix** [comment]
Bump.

**Comment by felixbuenemann** [comment]
I'm no fan of using `yield` when `&block` is passed int he arguments, but it's faster even with the optimizations to `Proc#call` in MRI 2.3.0 (see [Ruby Feature #11569](https://bugs.ruby-lang.org/issues/11569)).

Thanks, @ioquatix!

**Comment by ioquatix** [comment]
It might be possible to consider whether chaining `{ yield }` which avoids block argument might be another useful approach. In theory, MRI could easily identify this case and optimise it.

**Comment by felixbuenemann** [comment]
Can you post a short snippet? Not sure what you mean by "chaining yield".

**Comment by ioquatix** [comment]
```ruby
def recurse(n=10)
  yield n
  
  recurse(n-1) {|n| yield n} unless n == 0
end

> recurse {|n| puts n}                                             
10
9
8
7
6
5
4
3
2
1
0
=> nil
```

**Comment by ioquatix** [comment]
(as an alternative/improvement on:)

```ruby
def recurse(n=10, &block)
  yield n

  recurse(n-1, &block) unless n == 0
end

> recurse {|n| puts n}                                             
10
9
8
7
6
5
4
3
2
1
0
=> nil
```

**Comment by felixbuenemann** [comment]
Thanks, I missed your comment from Nov 26th.
I'd be happy to accept a PR that gets rid of the `&block` argument.

**Comment by ioquatix** [comment]
The only problem is I'm not sure if the performance is good... especially for deep tree. What is worse? Chaining yield or passing block argument. I suspect the block argument is only constructed once?

**Comment by felixbuenemann** [comment]
You could adjust your benchmark script above to find out and try a few tree depths.

**Comment by ioquatix** [comment]
I'd love to but it's 12:33 AM and I have some stuff I need to finish for tomorrow, sorry dude :)

**Comment by felixbuenemann** [comment]
No rush.

**Pull request merged**
